namespace Orchestra.Engine;

/// <summary>
/// An image attachment to send with a prompt to the LLM.
/// Supports both file paths (read from disk) and inline base64 blob data.
/// </summary>
public abstract class ImageAttachment
{
	/// <summary>
	/// Optional display name for the attachment.
	/// </summary>
	public string? DisplayName { get; init; }
}

/// <summary>
/// An image attachment referencing a file on disk.
/// The runtime reads the file, converts it to base64, and sends it to the LLM.
/// Supports template expressions (e.g., {{stepName.output}} for dynamically generated paths).
/// </summary>
public class FileImageAttachment : ImageAttachment
{
	/// <summary>
	/// Absolute path to the image file. Supports template expressions.
	/// </summary>
	public required string Path { get; init; }
}

/// <summary>
/// An image attachment with inline base64-encoded data.
/// Useful when the image is already in memory (e.g., generated by a previous step).
/// </summary>
public class BlobImageAttachment : ImageAttachment
{
	/// <summary>
	/// Base64-encoded image data. Supports template expressions
	/// (e.g., {{stepName.output}} for data produced by a prior step).
	/// </summary>
	public required string Data { get; init; }

	/// <summary>
	/// MIME type of the image (e.g., "image/png", "image/jpeg").
	/// </summary>
	public required string MimeType { get; init; }
}
